config/routes.rb
Rails.application.routes.draw do
  root 'meals#index'
  resources :meals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController

  def index
    @meal = Meal.order("RANDOM()").first
  end

  def new
    @meal = Meal.new
  end
   




  def create
    @meal = Meal.create(meal_params)
    redirect_to root_path
  end

  private


  def meal_params
    params.require(:meal).permit(:title, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Restaurant</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="row">
    </header>

   <%= yield %>

  </body>

  <%= link_to 'Order meal', new_meal_path %>
</html>

app/views/meals/index.html.erb
<h1>Welcome To my Fine Dining Restaurant</h1>
 <br /> <br />


 <u>Enjoy Our Exquisite meal courses<</u> Check our wine list too!


 <br />
 <br />

<h1><%= @meal.inspect %></h1>

app/views/meals/new.html.erb
<h1>Select your Meal Course</h1>
<h2> Please have a look at our Wine list.</h2>

<%= simple_form_for @meal do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit :'Order meal' %>

<% end %>

<%= link_to 'Homepage', root_path %>